"""Add teams table

Revision ID: 65afd33b61d7
Revises: daabe73eaa3d
Create Date: 2022-05-10 20:38:32.934356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65afd33b61d7'
down_revision = 'daabe73eaa3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('win_streak', sa.Integer(), nullable=False),
    sa.Column('loss_streak', sa.Integer(), nullable=False),
    sa.Column('leaderboard_position', sa.Integer(), nullable=True),
    sa.Column('image_source', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
