"""Add seasons table

Revision ID: 820a3338d095
Revises: 2cf9b8e86101
Create Date: 2022-05-10 08:29:33.665009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820a3338d095'
down_revision = '2cf9b8e86101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    # ### end Alembic commands ###
