"""Add players table

Revision ID: c00df37317be
Revises: 
Create Date: 2022-05-08 14:42:45.677119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00df37317be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('points', sa.String(length=64), nullable=False),
    sa.Column('rebounds', sa.String(length=64), nullable=False),
    sa.Column('assists', sa.String(length=64), nullable=False),
    sa.Column('steals', sa.String(length=64), nullable=False),
    sa.Column('blocks', sa.String(length=64), nullable=False),
    sa.Column('performance_index_rating', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_surname'), 'players', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_surname'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
